


[colors.primary]
background = '#000000'
foreground = '#ffffff'


[colors.cursor]
text = '#100b12'
#cursor = '#ffffff'


[colors.normal]
black = '#000000'
red = '#ff746c'
green = '#a6e3a1'
yellow = '#ffff99'
blue = '#b198d9'
magenta = '#ffc5d3'
cyan = '#94e2d5'
white = '#ffffff'

[colors.bright]
black = '#000000'
red = '#ff746c'
green = '#a6e3a1'
yellow = '#ffff99'
blue = '#b198d9'
magenta = '#ffc5d3'
cyan = '#94e2d5'
white = '#ffffff'

[colors.dim]
black = '#000000'
red = '#ff746c'
green = '#a6e3a1'
yellow = '#ffff99'
blue = '#b198d9'
magenta = '#ffc5d3'
cyan = '#94e2d5'
white = '#ffffff'
